development:
  adapter: postgresql
  encoding: utf8
  database: studiocracy_development
  host: localhost
  pool: 5
  user: postgres
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: studiocracy_test
  host: localhost
  pool: 5
  user: postgres
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: studiocracy_production
  host: localhost
  pool: 5
  user: postgres
  password: password
